// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/AddressBook.proto

package com.gn.protobuf;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .protobuf.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<com.gn.protobuf.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .protobuf.Person.PhoneNumber phones = 4;</code>
   */
  com.gn.protobuf.Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .protobuf.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .protobuf.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends com.gn.protobuf.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .protobuf.Person.PhoneNumber phones = 4;</code>
   */
  com.gn.protobuf.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
